os:
  - linux

language: c

install:
  - |
      echo "Install nim"
      wget http://nim-lang.org/download/nim-0.11.2.tar.xz
      tar xf nim-0.11.2.tar.xz
      cd nim-0.11.2
      sh build.sh
      cd ..
      echo "Install nimble"
      git clone https://github.com/nim-lang/nimble.git
      cd nimble
      nim c -r src/nimble install
      cd ..

before_script:
  - set -e
  - set -x
  - export PATH=`pwd`/nim-0.11.2/bin:$PATH

script:
  - |
      nimble build
      make all

notifications:
  email: false
