os:
  - linux

language: c

addons:
  apt:
    packages:
      - libxxf86vm-dev

install:
  - |
      echo "Install nim"
      wget http://nim-lang.org/download/nim-0.11.2.tar.xz
      tar xf nim-0.11.2.tar.xz
      cd nim-0.11.2
      sh build.sh
      export PATH=`pwd`/bin:$PATH
      cd ..
      echo "Install nimble"
      git clone https://github.com/nim-lang/nimble.git
      cd nimble
      nim c -r src/nimble install
      export PATH=~/.nimble/bin:$PATH
      cd ..

before_script:
  - set -e
  - set -x

script:
  - yes | make

notifications:
  email: false
